// ProjectHLN UI System v2 - build/assemble script.
// Generates ui-system/v2/dist from ui-system/v2/src and produces the
// self-contained hln-ui-system-v2.css bundle. Run: bun v2/build.mjs
import { readFile, writeFile, mkdir, cp } from "node:fs/promises"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const v2 = dirname(fileURLToPath(import.meta.url))
const src = join(v2, "src")
const dist = join(v2, "dist")

const copies = ["tokens.css", "themes.css", "base.css", "index.js", "index.d.ts", "runtime-transport.js", "runtime-transport.d.ts"]

await mkdir(dist, { recursive: true })
for (const file of copies) {
  await cp(join(src, file), join(dist, file))
}

const bundle = [
  await readFile(join(dist, "tokens.css"), "utf8"),
  await readFile(join(dist, "themes.css"), "utf8"),
  await readFile(join(dist, "base.css"), "utf8"),
].join("\n")

const banner =
  "/* ProjectHLN UI System v2 - self-contained distribution. Do not edit; generated by v2/build.mjs. */\n"
await writeFile(join(dist, "hln-ui-system-v2.css"), banner + bundle)
console.log("v2 dist assembled; bundle bytes:", (banner + bundle).length)