// ProjectHLN UI System v2 - 9-theme consistency contract (portable Node test)
// Locks the v2 catalog across source CSS, runtime registry, TS declarations,
// contract spec, README, and the generated dist bundle so any 6/9 drift regresses.
import test from "node:test"
import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"
import { HLN_V2_THEMES, HLN_V2_THEME_REGISTRY } from "./dist/index.js"

const v2 = dirname(fileURLToPath(import.meta.url))
const read = (rel) => readFileSync(join(v2, rel), "utf8")
const text = (rel) => read(rel)

const NINE = [
  "arknights",
  "endfield",
  "rhodes-island",
  "monster-siren",
  "rhine-lab",
  "blacksteel",
  "babel",
  "victoria-steam",
  "abyss-aegir",
]

function assertIncludesAll(artifact, label) {
  const missing = NINE.filter((id) => !artifact.includes(id))
  assert.deepEqual(missing, [], `${label} is missing theme ids: ${missing.join(", ")}`)
}

test("v2 runtime registry exposes exactly the 9 canonical themes", () => {
  assert.deepEqual([...HLN_V2_THEMES].sort(), [...NINE].sort())
  assert.equal(HLN_V2_THEMES.length, 9)
  const registryIds = HLN_V2_THEME_REGISTRY.map((t) => t.id)
  assert.deepEqual([...registryIds].sort(), [...NINE].sort(), "registry ids must equal the 9 canonical themes")
})

test("source CSS defines all 9 theme blocks", () => {
  assertIncludesAll(text("src/themes.css"), "src/themes.css")
})

test("runtime source & declarations list the 9 themes", () => {
  const js = text("src/index.js")
  const ts = text("src/index.d.ts")
  for (const id of NINE) {
    assert.ok(js.includes(`"${id}"`), `src/index.js missing theme id "${id}"`)
    assert.ok(ts.includes(`"${id}"`), `src/index.d.ts missing theme id "${id}"`)
  }
})

test("spec (contract.md) and README document the 9 themes", () => {
  assertIncludesAll(text("contract.md"), "contract.md")
  assertIncludesAll(text("README.md"), "README.md")
})

test("dist mirrors source for all bundled files", () => {
  for (const f of ["tokens.css", "themes.css", "base.css", "index.js", "index.d.ts"]) {
    assert.equal(text(`dist/${f}`), text(`src/${f}`), `dist/${f} drifted from src/${f}`)
  }
})

test("dist bundle is current and contains all 9 themes", () => {
  const banner = "/* ProjectHLN UI System v2 - self-contained distribution. Do not edit; generated by v2/build.mjs. */\n"
  const expected = banner + [
    text("src/tokens.css"),
    text("src/themes.css"),
    text("src/base.css"),
  ].join("\n")
  const bundle = text("dist/hln-ui-system-v2.css")
  assert.equal(bundle, expected, "dist/hln-ui-system-v2.css is stale; run node build.mjs")
  assertIncludesAll(bundle, "dist/hln-ui-system-v2.css")
})

test("registry accent/colorScheme/swatch match source CSS for all 9 themes", () => {
  const css = text("src/themes.css")
  for (const meta of HLN_V2_THEME_REGISTRY) {
    const blockStart = css.indexOf(`data-hln-theme="${meta.id}"`)
    assert.notEqual(blockStart, -1, `src/themes.css missing block for ${meta.id}`)
    const block = css.slice(blockStart)
    const accent = block.match(/--hln-ui-accent:\s*([^;]+);/)
    const swatch = block.match(/--hln-ui-bg-1:\s*([^;]+);/)
    const scheme = block.match(/color-scheme:\s*([a-z]+);/)
    assert.equal(accent?.[1]?.trim(), meta.accent, `${meta.id} accent mismatch vs CSS`)
    assert.equal(swatch?.[1]?.trim(), meta.swatch, `${meta.id} swatch (bg-1) mismatch vs CSS`)
    assert.equal(scheme?.[1], meta.colorScheme, `${meta.id} colorScheme mismatch vs CSS`)
  }
})

test("portable verify passes against the built bundle", () => {
  const bundle = text("dist/hln-ui-system-v2.css")
  const fonts = ["display", "body", "classic", "technical"]
  for (const f of fonts) assert.ok(bundle.includes(`data-hln-font="${f}"`), `bundle missing font ${f}`)
  const kinetics = ["panel", "item", "spring", "cyber-scan", "blur-zoom", "wipe-reveal", "quantum-glitch", "radar-sweep", "prism-burst"]
  for (const k of kinetics) assert.ok(bundle.includes(k), `bundle missing kinetic ${k}`)
  const bg = ["tactical-grid", "holo-scan", "nebula-flow", "prts-sonar", "quantum-wave", "aurora", "quiet"]
  for (const b of bg) assert.ok(bundle.includes(`data-hln-bg-motion="${b}"`), `bundle missing bg preset ${b}`)
})
