// ProjectHLN UI System v2.3 - 6-theme industrial-tactical consistency contract
// Locks the v2.3 catalog across source CSS, runtime registry, TS declarations,
// contract spec, README, and the generated dist bundle so any drift regresses.
import test from "node:test"
import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"
import { HLN_V23_THEMES, HLN_V23_THEME_REGISTRY, HLN_V23_FONTS, HLN_V23_BG_PRESETS } from "./dist/index.js"

const Q = String.fromCharCode(34)
const v23 = dirname(fileURLToPath(import.meta.url))
const read = (rel) => readFileSync(join(v23, rel), "utf8")

const SIX = ["arknights", "endfield", "blacksteel", "abyss-aegir", "babel", "monster-siren"]
const FONTS = ["display", "technical", "grotesque", "cyber", "berlin", "condensed"]
const BG = ["tactical-grid", "holo-scan", "circuit-trace", "prts-sonar", "hazard-hatch", "hex-field", "radar-cross", "data-rain", "blueprint", "data-lattice", "blueprint-schematic", "quiet"]
const MOTION = ["panel", "item", "cyber-scan", "wipe-reveal", "radar-sweep", "clip-scan", "tactical-lock", "data-stream", "grid-march", "scanline-decode", "corner-deploy", "radar-deploy", "pulse-chain", "signal-sweep"]

function assertIncludesAll(artifact, label, ids) {
  const missing = ids.filter((id) => !artifact.includes(id))
  assert.deepEqual(missing, [], label + " is missing ids: " + missing.join(", "))
}

test("v2.3 runtime registry exposes exactly the 6 industrial themes", () => {
  assert.deepEqual([...HLN_V23_THEMES].sort(), [...SIX].sort())
  assert.equal(HLN_V23_THEMES.length, 6)
  const registryIds = HLN_V23_THEME_REGISTRY.map((t) => t.id)
  assert.deepEqual([...registryIds].sort(), [...SIX].sort(), "registry ids must equal the 4 canonical themes")
})

test("source CSS defines all 6 theme blocks", () => {
  assertIncludesAll(read("src/themes.css"), "src/themes.css", SIX)
})

test("runtime source & declarations list the 6 themes", () => {
  const js = read("src/index.js")
  const ts = read("src/index.d.ts")
  for (const id of SIX) {
    assert.ok(js.includes(Q + id + Q), "src/index.js missing theme id " + id)
    assert.ok(ts.includes(Q + id + Q), "src/index.d.ts missing theme id " + id)
  }
})

test("fonts, bg presets & motion are the curated v2.3 sets", () => {
  assert.deepEqual([...HLN_V23_FONTS], FONTS)
  assert.deepEqual(HLN_V23_BG_PRESETS.map((b) => b.id), BG)
})

test("spec (contract.md) and README document the 6 themes", () => {
  assertIncludesAll(read("contract.md"), "contract.md", SIX)
  assertIncludesAll(read("README.md"), "README.md", SIX)
})

test("dist mirrors source for all bundled files", () => {
  for (const f of ["tokens.css", "themes.css", "base.css", "index.js", "index.d.ts"]) {
    assert.equal(read("dist/" + f), read("src/" + f), "dist/" + f + " drifted from src/" + f)
  }
})

test("dist bundle is current and contains all 6 themes", () => {
  const banner = "/* ProjectHLN UI System v2.3 - self-contained distribution. Do not edit; generated by v2.3/build.mjs. " + "*/" + String.fromCharCode(10)
  const expected = banner + [
    read("src/tokens.css"),
    read("src/themes.css"),
    read("src/base.css"),
  ].join(String.fromCharCode(10))
  const bundle = read("dist/hln-ui-system-v2.3.css")
  assert.equal(bundle, expected, "dist/hln-ui-system-v2.3.css is stale; run node build.mjs")
  assertIncludesAll(bundle, "dist/hln-ui-system-v2.3.css", SIX)
})

test("registry accent/colorScheme/swatch match source CSS for all 6 themes", () => {
  const css = read("src/themes.css")
  for (const meta of HLN_V23_THEME_REGISTRY) {
    const blockStart = css.indexOf("data-hln-theme=" + Q + meta.id + Q)
    assert.notEqual(blockStart, -1, "src/themes.css missing block for " + meta.id)
    const block = css.slice(blockStart)
    const accent = block.match(/--hln-ui-accent:\s*([^;]+);/)
    const swatch = block.match(/--hln-ui-bg-1:\s*([^;]+);/)
    const scheme = block.match(/color-scheme:\s*([a-z]+);/)
    assert.equal(accent?.[1]?.trim(), meta.accent, meta.id + " accent mismatch vs CSS")
    assert.equal(swatch?.[1]?.trim(), meta.swatch, meta.id + " swatch (bg-1) mismatch vs CSS")
    assert.equal(scheme?.[1], meta.colorScheme, meta.id + " colorScheme mismatch vs CSS")
  }
})

test("bundle is curated: fonts, motion, bg present and dropped v2 items absent", () => {
  const bundle = read("dist/hln-ui-system-v2.3.css")
  for (const f of FONTS) assert.ok(bundle.includes("data-hln-font=" + Q + f + Q), "bundle missing font " + f)
  for (const k of MOTION) assert.ok(bundle.includes(k), "bundle missing kinetic " + k)
  for (const b of BG) assert.ok(bundle.includes("data-hln-bg-motion=" + Q + b + Q), "bundle missing bg preset " + b)
  for (const d of ["nebula-flow", "quantum-wave", "prism-burst", "blur-zoom", "aurora-veil", "data-hln-font=" + Q + "fangsong" + Q, "data-hln-font=" + Q + "classic" + Q, "data-hln-font=" + Q + "body" + Q]) {
    assert.ok(!bundle.includes(d), "bundle must not contain dropped item " + d)
  }
})
