// ProjectHLN UI System v2.5 - linear editorial vector consistency contract
// Locks the v2.5 catalog across source CSS, runtime registry, TS declarations,
// contract spec, README, and the generated dist bundle so any drift regresses.
import test from "node:test"
import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"
import {
  HLN_V25_THEMES,
  HLN_V25_THEME_REGISTRY,
  HLN_V25_FONTS,
  HLN_V25_BG_PRESETS,
} from "./dist/index.js"

const Q = String.fromCharCode(34)
const v25 = dirname(fileURLToPath(import.meta.url))
const read = (rel) => readFileSync(join(v25, rel), "utf8")

const THEMES = [
  "arknights",
  "endfield",
  "blacksteel",
  "abyss-aegir",
  "babel",
  "monster-siren",
  "rhodes-paper",
  "lungmen-night",
  "kazdel-ink",
]
const FONTS = ["display", "technical", "grotesque", "cyber", "berlin", "condensed", "editorial", "label"]
const BG = [
  "tactical-grid",
  "holo-scan",
  "circuit-trace",
  "prts-sonar",
  "hazard-hatch",
  "hex-field",
  "radar-cross",
  "data-rain",
  "blueprint",
  "data-lattice",
  "blueprint-schematic",
  "editorial-grid",
  "quiet",
]
const MOTION = [
  "panel",
  "item",
  "cyber-scan",
  "wipe-reveal",
  "radar-sweep",
  "clip-scan",
  "tactical-lock",
  "data-stream",
  "grid-march",
  "scanline-decode",
  "corner-deploy",
  "radar-deploy",
  "pulse-chain",
  "signal-sweep",
  "rail-draw",
  "type-in",
  "page-shift",
]

function assertIncludesAll(artifact, label, ids) {
  const missing = ids.filter((id) => !artifact.includes(id))
  assert.deepEqual(missing, [], label + " is missing ids: " + missing.join(", "))
}

test("v2.5 runtime registry exposes exactly the 9 linear editorial themes", () => {
  assert.deepEqual([...HLN_V25_THEMES].sort(), [...THEMES].sort())
  assert.equal(HLN_V25_THEMES.length, 9)
  const registryIds = HLN_V25_THEME_REGISTRY.map((t) => t.id)
  assert.deepEqual([...registryIds].sort(), [...THEMES].sort(), "registry ids must equal the 9 canonical themes")
})

test("source CSS defines all 9 theme blocks", () => {
  assertIncludesAll(read("src/themes.css"), "src/themes.css", THEMES)
})

test("runtime source & declarations list the 9 themes", () => {
  const js = read("src/index.js")
  const ts = read("src/index.d.ts")
  for (const id of THEMES) {
    assert.ok(js.includes(Q + id + Q), "src/index.js missing theme id " + id)
    assert.ok(ts.includes(Q + id + Q), "src/index.d.ts missing theme id " + id)
  }
})

test("fonts, bg presets & motion are the curated v2.5 sets", () => {
  assert.deepEqual([...HLN_V25_FONTS], FONTS)
  assert.deepEqual(HLN_V25_BG_PRESETS.map((b) => b.id), BG)
})

test("spec (contract.md) and README document the 9 themes", () => {
  assertIncludesAll(read("contract.md"), "contract.md", THEMES)
  assertIncludesAll(read("README.md"), "README.md", THEMES)
})

test("dist mirrors source for all bundled files", () => {
  for (const f of ["tokens.css", "themes.css", "base.css", "edition.css", "index.js", "index.d.ts"]) {
    assert.equal(read("dist/" + f), read("src/" + f), "dist/" + f + " drifted from src/" + f)
  }
})

test("dist bundle is current and contains all 9 themes", () => {
  const banner = "/* ProjectHLN UI System v2.5 - self-contained distribution. Do not edit; generated by v2.5/build.mjs. " + "*/" + String.fromCharCode(10)
  const expected = banner + [
    read("src/tokens.css"),
    read("src/themes.css"),
    read("src/base.css"),
    read("src/edition.css"),
  ].join(String.fromCharCode(10))
  const bundle = read("dist/hln-ui-system-v2.5.css")
  assert.equal(bundle, expected, "dist/hln-ui-system-v2.5.css is stale; run node build.mjs")
  assertIncludesAll(bundle, "dist/hln-ui-system-v2.5.css", THEMES)
})

test("registry accent/colorScheme/swatch match source CSS for all 9 themes", () => {
  const css = read("src/themes.css")
  for (const meta of HLN_V25_THEME_REGISTRY) {
    const blockStart = css.indexOf("data-hln-theme=" + Q + meta.id + Q)
    assert.notEqual(blockStart, -1, "src/themes.css missing block for " + meta.id)
    const block = css.slice(blockStart)
    const accent = block.match(/--hln-ui-accent:\s*([^;]+);/)
    const swatch = block.match(/--hln-ui-bg-1:\s*([^;]+);/)
    const scheme = block.match(/color-scheme:\s*([a-z]+);/)
    assert.equal(accent?.[1]?.trim(), meta.accent, meta.id + " accent mismatch vs CSS")
    assert.equal(swatch?.[1]?.trim(), meta.swatch, meta.id + " swatch (bg-1) mismatch vs CSS")
    assert.equal(scheme?.[1], meta.colorScheme, meta.id + " colorScheme mismatch vs CSS")
  }
})

test("bundle is curated: fonts, motion, bg present and dropped v2 items absent", () => {
  const bundle = read("dist/hln-ui-system-v2.5.css")
  for (const f of FONTS) assert.ok(bundle.includes("data-hln-font=" + Q + f + Q), "bundle missing font " + f)
  for (const k of MOTION) assert.ok(bundle.includes(k), "bundle missing kinetic " + k)
  for (const b of BG) assert.ok(bundle.includes("data-hln-bg-motion=" + Q + b + Q), "bundle missing bg preset " + b)
  for (const d of ["nebula-flow", "quantum-wave", "prism-burst", "blur-zoom", "aurora-veil", "data-hln-font=" + Q + "fangsong" + Q, "data-hln-font=" + Q + "classic" + Q, "data-hln-font=" + Q + "body" + Q]) {
    assert.ok(!bundle.includes(d), "bundle must not contain dropped item " + d)
  }
})

test("edition layer contains the linear editorial workbench contract", () => {
  const edition = read("src/edition.css")
  assertIncludesAll(edition, "src/edition.css", [
    "hln-v25-workbench",
    "hln-v25-command-strip",
    "hln-v25-rail",
    "hln-v25-stage",
    "hln-v25-section",
    "hln-v25-metric-row",
    "hln-v25-data-list",
    "hln-v25-swatch-grid",
    "hln-v25-status",
    "hln-v25-rail-draw",
    "hln-v25-type-in",
    "hln-v25-page-shift",
  ])
})

test("edition refinement preserves readable and touch-safe controls", () => {
  const edition = read("src/edition.css")
  const tokens = read("src/tokens.css")
  assertIncludesAll(edition, "src/edition.css refinement", [
    "font-size: 15px",
    "outline: 2px solid var(--hln-ui-focus)",
    "touch-action: manipulation",
    "min-height: 44px",
    "overflow-wrap: anywhere",
  ])
  assert.ok(tokens.includes("--hln-ui-title-size: 2.25rem"), "title size must be stable")
  assert.ok(!tokens.includes("--hln-ui-title-size: clamp"), "title size must not scale with viewport width")
})
