// ProjectHLN UI System v3.2 - Build Script
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const root = dirname(fileURLToPath(import.meta.url))
const src = join(root, "src")
const dist = join(root, "dist")
mkdirSync(dist, { recursive: true })

const files = ["tokens.css", "themes.css", "base.css", "linear.css", "index.js", "index.d.ts"]
for (const f of files) {
  copyFileSync(join(src, f), join(dist, f))
}

const banner = "/* ProjectHLN UI System v3.2 - Subtractive Linear Architecture Edition. Do not edit; generated by v3.2/build.mjs. */\n"
const bundle =
  banner +
  ["tokens.css", "themes.css", "base.css", "linear.css"]
    .map((f) => readFileSync(join(src, f), "utf8"))
    .join("\n")

writeFileSync(join(dist, "hln-ui-system-v3.2.css"), bundle, "utf8")
console.log("v3.2 dist assembled; bundle bytes:", Buffer.byteLength(bundle, "utf8"))
