// ProjectHLN UI System v3.2 - Subtractive Linear Architecture Contract Tests
import test from "node:test"
import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"
import {
  HLN_V32_THEMES,
  HLN_V32_THEME_REGISTRY,
  HLN_V32_FONTS,
  HLN_V32_BG_PRESETS,
  HLN_V32_MATH_CONSTANTS,
} from "./dist/index.js"

const Q = String.fromCharCode(34)
const v32 = dirname(fileURLToPath(import.meta.url))
const read = (rel) => readFileSync(join(v32, rel), "utf8")

const THEMES = [
  "linear-obsidian",
  "linear-platinum",
  "linear-amber",
  "linear-paper",
  "linear-emerald",
  "linear-mono",
]
const FONTS = ["geometric", "grotesque", "editorial", "technical", "display"]
const BG = ["horizon-rule", "axial-cross", "parallel-lines", "fine-grain-line", "quiet"]
const MOTION = ["panel", "item", "line-extend", "plane-glide", "axis-reveal", "rail-draw", "type-in", "page-shift"]

test("v3.2 runtime registry exposes the 6 subtractive linear themes with zero game terminology", () => {
  assert.deepEqual([...HLN_V32_THEMES].sort(), [...THEMES].sort())
  assert.equal(HLN_V32_THEMES.length, 6)
  assert.deepEqual(HLN_V32_THEME_REGISTRY.map((t) => t.id).sort(), [...THEMES].sort())
  const bundle = read("dist/hln-ui-system-v3.2.css").toLowerCase()
  const js = read("dist/index.js").toLowerCase()
  for (const banned of ["prts", "arknights", "endfield", "rhodes", "blacksteel", "aegir", "babel", "rhine", "kazdel", "lungmen", "monster-siren"]) {
    assert.ok(!bundle.includes(banned), `v3.2 CSS bundle must not contain game term "${banned}"`)
    assert.ok(!js.includes(banned), `v3.2 JS runtime must not contain game term "${banned}"`)
  }
})

test("v3.2 mathematical constants are exact", () => {
  assert.ok(Math.abs(HLN_V32_MATH_CONSTANTS.PHI - 1.6180339887) < 1e-8)
  assert.ok(Math.abs(HLN_V32_MATH_CONSTANTS.SQRT2 - 1.4142135623) < 1e-8)
})

test("v3.2 source CSS defines all 6 linear themes with zero blur and zero shadow", () => {
  const css = read("src/themes.css")
  for (const meta of HLN_V32_THEME_REGISTRY) {
    const blockStart = css.indexOf("data-hln-theme=" + Q + meta.id + Q)
    assert.notEqual(blockStart, -1, "src/themes.css missing block for " + meta.id)
    const block = css.slice(blockStart)
    const accent = block.match(/--hln-ui-accent:\s*([^;]+);/)
    const swatch = block.match(/--hln-ui-bg-1:\s*([^;]+);/)
    const scheme = block.match(/color-scheme:\s*([a-z]+);/)
    const blur = block.match(/--hln-ui-blur:\s*([^;]+);/)
    const shadow = block.match(/--hln-ui-shadow:\s*([^;]+);/)
    assert.equal(accent?.[1]?.trim(), meta.accent, meta.id + " accent mismatch vs CSS")
    assert.equal(swatch?.[1]?.trim(), meta.swatch, meta.id + " swatch mismatch vs CSS")
    assert.equal(scheme?.[1], meta.colorScheme, meta.id + " colorScheme mismatch vs CSS")
    assert.equal(blur?.[1]?.trim(), "0px", meta.id + " must enforce --hln-ui-blur: 0px")
    assert.equal(shadow?.[1]?.trim(), "none", meta.id + " must enforce --hln-ui-shadow: none")
  }
})

test("v3.2 dist mirrors source and bundle is current", () => {
  for (const f of ["tokens.css", "themes.css", "base.css", "linear.css", "index.js", "index.d.ts"]) {
    assert.equal(read("dist/" + f), read("src/" + f), "dist/" + f + " drifted from src/" + f)
  }
  const banner = "/* ProjectHLN UI System v3.2 - Subtractive Linear Architecture Edition. Do not edit; generated by v3.2/build.mjs. */\n"
  const expected = banner + ["tokens.css", "themes.css", "base.css", "linear.css"].map((f) => read("src/" + f)).join("\n")
  assert.equal(read("dist/hln-ui-system-v3.2.css"), expected)
})

test("v3.2 linear architecture layer includes open horizon, 1px columns, linear artboard, and operator rows", () => {
  const lin = read("src/linear.css")
  for (const cls of [
    "hln-v32-shell",
    "hln-v32-horizon",
    "hln-v32-columns",
    "hln-v32-col",
    "hln-v32-sec-head",
    "hln-v32-artboard",
    "hln-v32-ratio-strip",
    "hln-v32-ratio-pill",
    "hln-v32-operator-list",
    "hln-v32-sequence",
    "hln-v32-line-meter",
  ]) {
    assert.ok(lin.includes(cls), "src/linear.css missing class " + cls)
  }
})

test("v3.2 fonts, backgrounds & motion match curated subtractive sets", async () => {
  assert.deepEqual([...HLN_V32_FONTS], FONTS)
  assert.deepEqual(HLN_V32_BG_PRESETS.map((b) => b.id), BG)
  const bundle = read("dist/hln-ui-system-v3.2.css")
  for (const f of FONTS) assert.ok(bundle.includes("data-hln-font=" + Q + f + Q), "bundle missing font " + f)
  for (const k of MOTION) assert.ok(bundle.includes(k), "bundle missing motion " + k)
  for (const b of BG) assert.ok(bundle.includes("data-hln-bg-motion=" + Q + b + Q), "bundle missing bg preset " + b)
  const { HLN_V32_CJK_FONTS } = await import("./dist/index.js")
  assert.deepEqual([...HLN_V32_CJK_FONTS], ["auto", "hei", "display", "song", "kai", "mono", "fangsong"])
  assert.ok(bundle.includes("--hln-ui-font-cjk-hei:"), "v3.2 bundle missing --hln-ui-font-cjk-hei token")
  assert.ok(bundle.includes("font-size-adjust: from-font"), "v3.2 bundle missing font-size-adjust: from-font")
})

