// ProjectHLN UI System v3.0 - build/assemble script.
// Generates ui-source/v3/dist from ui-source/v3/src and produces the
// self-contained hln-ui-system-v3.css bundle. Run: node v3/build.mjs
import { readFile, writeFile, mkdir, cp } from "node:fs/promises"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const v3 = dirname(fileURLToPath(import.meta.url))
const src = join(v3, "src")
const dist = join(v3, "dist")

const copies = ["tokens.css", "themes.css", "base.css", "geometry.css", "index.js", "index.d.ts"]

await mkdir(dist, { recursive: true })
for (const file of copies) {
  await cp(join(src, file), join(dist, file))
}

const bundle = [
  await readFile(join(dist, "tokens.css"), "utf8"),
  await readFile(join(dist, "themes.css"), "utf8"),
  await readFile(join(dist, "base.css"), "utf8"),
  await readFile(join(dist, "geometry.css"), "utf8"),
].join("\n")

const banner =
  "/* ProjectHLN UI System v3.0 - Euclidean Vector Flat Edition. Do not edit; generated by v3/build.mjs. */\n"
await writeFile(join(dist, "hln-ui-system-v3.css"), banner + bundle)
console.log("v3 dist assembled; bundle bytes:", (banner + bundle).length)
