// ProjectHLN UI System v3.0 - Euclidean Vector Flat, Numerical & Mathematical Geometry Contract Tests
import test from "node:test"
import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"
import {
  HLN_V3_THEMES,
  HLN_V3_THEME_REGISTRY,
  HLN_V3_FONTS,
  HLN_V3_BG_PRESETS,
  HLN_V3_MATH_CONSTANTS,
} from "./dist/index.js"

const Q = String.fromCharCode(34)
const v3 = dirname(fileURLToPath(import.meta.url))
const read = (rel) => readFileSync(join(v3, rel), "utf8")

const THEMES = [
  "euclidean-cyan",
  "isometric-amber",
  "drafting-paper",
  "bauhaus-grid",
  "cartesian-emerald",
  "graphite-polygon",
  "polar-cobalt",
  "hypercube-violet",
  "axiom-mono",
]
const FONTS = ["geometric", "display", "technical", "grotesque", "cyber", "berlin", "editorial", "label"]
const BG = [
  "euclidean-grid",
  "golden-spiral",
  "isometric-lattice",
  "polar-locus",
  "bezier-field",
  "voronoi-poly",
  "hex-field",
  "blueprint-schematic",
  "swiss-dots",
  "quiet",
]
const MOTION = [
  "panel",
  "item",
  "vector-construct",
  "golden-iris",
  "iso-shift",
  "polygon-unfold",
  "axis-snap",
  "vertex-lock",
  "wipe-reveal",
  "clip-scan",
  "rail-draw",
  "type-in",
  "page-shift",
]

function assertIncludesAll(artifact, label, ids) {
  const missing = ids.filter((id) => !artifact.includes(id))
  assert.deepEqual(missing, [], label + " is missing ids: " + missing.join(", "))
}

test("v3 runtime registry exposes the 9 Euclidean vector-flat themes with zero game terminology", () => {
  assert.deepEqual([...HLN_V3_THEMES].sort(), [...THEMES].sort())
  assert.equal(HLN_V3_THEMES.length, 9)
  const registryIds = HLN_V3_THEME_REGISTRY.map((t) => t.id)
  assert.deepEqual([...registryIds].sort(), [...THEMES].sort())
  const bundle = read("dist/hln-ui-system-v3.css").toLowerCase()
  const js = read("dist/index.js").toLowerCase()
  for (const banned of ["prts", "arknights", "endfield", "rhodes", "blacksteel", "aegir", "babel", "rhine", "kazdel", "lungmen", "monster-siren"]) {
    assert.ok(!bundle.includes(banned), `v3 CSS bundle must not contain game term "${banned}"`)
    assert.ok(!js.includes(banned), `v3 JS runtime must not contain game term "${banned}"`)
  }
})

test("v3 mathematical constants are exact", () => {
  assert.ok(Math.abs(HLN_V3_MATH_CONSTANTS.PHI - 1.6180339887) < 1e-8)
  assert.ok(Math.abs(HLN_V3_MATH_CONSTANTS.SQRT2 - 1.4142135623) < 1e-8)
  assert.ok(Math.abs(HLN_V3_MATH_CONSTANTS.SQRT3 - 1.7320508075) < 1e-8)
})

test("source CSS defines all 9 theme blocks with zero blur", () => {
  const css = read("src/themes.css")
  assertIncludesAll(css, "src/themes.css", THEMES)
  for (const meta of HLN_V3_THEME_REGISTRY) {
    const blockStart = css.indexOf("data-hln-theme=" + Q + meta.id + Q)
    assert.notEqual(blockStart, -1, "src/themes.css missing block for " + meta.id)
    const block = css.slice(blockStart)
    const accent = block.match(/--hln-ui-accent:\s*([^;]+);/)
    const swatch = block.match(/--hln-ui-bg-1:\s*([^;]+);/)
    const scheme = block.match(/color-scheme:\s*([a-z]+);/)
    const blur = block.match(/--hln-ui-blur:\s*([^;]+);/)
    assert.equal(accent?.[1]?.trim(), meta.accent, meta.id + " accent mismatch vs CSS")
    assert.equal(swatch?.[1]?.trim(), meta.swatch, meta.id + " swatch (bg-1) mismatch vs CSS")
    assert.equal(scheme?.[1], meta.colorScheme, meta.id + " colorScheme mismatch vs CSS")
    assert.equal(blur?.[1]?.trim(), "0px", meta.id + " must enforce --hln-ui-blur: 0px for flat vector plane")
  }
})

test("dist mirrors source and bundle is up-to-date", () => {
  for (const f of ["tokens.css", "themes.css", "base.css", "geometry.css", "index.js", "index.d.ts"]) {
    assert.equal(read("dist/" + f), read("src/" + f), "dist/" + f + " drifted from src/" + f)
  }
  const banner = "/* ProjectHLN UI System v3.0 - Euclidean Vector Flat Edition. Do not edit; generated by v3/build.mjs. */\n"
  const expected = banner + [
    read("src/tokens.css"),
    read("src/themes.css"),
    read("src/base.css"),
    read("src/geometry.css"),
  ].join("\n")
  assert.equal(read("dist/hln-ui-system-v3.css"), expected)
})

test("geometry layer includes mathematical proportion grids, numerical typography, and vector diagram primitives", () => {
  const geo = read("src/geometry.css")
  assertIncludesAll(geo, "src/geometry.css", [
    "hln-v3-golden-grid",
    "hln-v3-silver-grid",
    "hln-v3-workbench",
    "hln-v3-axis-bar",
    "hln-v3-card",
    "hln-v3-ruler-scale",
    "hln-v3-num-grid",
    "hln-v3-num-card",
    "hln-v3-diagram",
    "hln-v3-fibonacci-box",
    "hln-v3-transform-matrix",
    "hln-v3-quant-meter",
    "hln-v3-metric-matrix",
    "hln-v3-spec-list",
  ])
})

test("fonts, bg presets & motion match curated v3 sets", () => {
  assert.deepEqual([...HLN_V3_FONTS], FONTS)
  assert.deepEqual(HLN_V3_BG_PRESETS.map((b) => b.id), BG)
  const bundle = read("dist/hln-ui-system-v3.css")
  for (const f of FONTS) assert.ok(bundle.includes("data-hln-font=" + Q + f + Q), "bundle missing font " + f)
  for (const k of MOTION) assert.ok(bundle.includes(k), "bundle missing kinetic " + k)
  for (const b of BG) assert.ok(bundle.includes("data-hln-bg-motion=" + Q + b + Q), "bundle missing bg preset " + b)
})

test("artist-Paralos-main HTML and JS integrate all 5 UI engines (v1, v2, v2.3, v2.5, v3) and synced bundles", () => {
  const html = read("../../artist-Paralos-main/index.html")
  const appJs = read("../../artist-Paralos-main/app.js")
  for (const ver of ["v1", "v2", "v2.3", "v2.5", "v3"]) {
    assert.ok(html.includes(`data-ui-version="${ver}"`), `index.html missing switcher button for ${ver}`)
    assert.ok(appJs.includes(`"${ver}"`) || appJs.includes(`${ver}:`), `app.js missing version wiring for ${ver}`)
  }
  for (const cssFile of [
    "hln-ui-system.css",
    "hln-ui-system-v2.css",
    "hln-ui-system-v2.3.css",
    "hln-ui-system-v2.5.css",
    "hln-ui-system-v3.css",
  ]) {
    const content = read(`../../artist-Paralos-main/styles/${cssFile}`)
    assert.ok(content.length > 1000, `artist-Paralos-main/styles/${cssFile} is missing or empty`)
  }
  assert.equal(
    read("../../artist-Paralos-main/styles/hln-ui-system-v3.css"),
    read("dist/hln-ui-system-v3.css"),
    "artist-Paralos-main/styles/hln-ui-system-v3.css drifted from v3 dist bundle"
  )
})

test("v3 enforces single-hairline vector discipline, animated backgrounds, and staggered motion", () => {
  const bundle = read("dist/hln-ui-system-v3.css")
  assert.ok(!bundle.includes("scrollbar-color:"), "v3 must not set scrollbar-color which causes OS native triangle buttons")
  assert.ok(bundle.includes("::-webkit-scrollbar-button"), "v3 must explicitly hide ::-webkit-scrollbar-button")
  assert.ok(!bundle.includes("2px 2px 0"), "v3 must not render duplicate 2px offset ghost shadows")
  assert.ok(!bundle.includes("3px 3px 0"), "v3 must not render duplicate 3px offset ghost shadows")
  for (const bgAnim of [
    "hln-v3-bg-cartesian-drift",
    "hln-v3-bg-axis-sweep",
    "hln-v3-bg-phi-harmonic",
    "hln-v3-bg-iso-glide",
    "hln-v3-bg-plane-phase",
    "hln-v3-bg-polar-rotate",
    "hln-v3-bg-bezier-pan",
    "hln-v3-bg-node-pulse",
    "hln-v3-bg-poly-shift",
    "hln-v3-bg-hex-drift",
    "hln-v3-bg-blueprint-march",
    "hln-v3-bg-vertical-scan",
    "hln-v3-bg-dots-drift",
  ]) {
    assert.ok(bundle.includes(`@keyframes ${bgAnim}`), `v3 bundle missing background animation @keyframes ${bgAnim}`)
  }
})

test("v3 defines curated CJK Hanzi typography stacks, font-size-adjust calibration, and runtime CJK font modes", async () => {
  const { HLN_V3_CJK_FONTS, HLN_V3_CJK_FONT_REGISTRY } = await import("./dist/index.js")
  assert.deepEqual([...HLN_V3_CJK_FONTS], ["auto", "hei", "display", "song", "kai", "mono", "fangsong"])
  assert.equal(HLN_V3_CJK_FONT_REGISTRY.length, 7)
  const bundle = read("dist/hln-ui-system-v3.css")
  assert.ok(bundle.includes("--hln-ui-font-cjk-hei:"), "v3 bundle missing --hln-ui-font-cjk-hei token")
  assert.ok(bundle.includes("--hln-ui-font-cjk-song:"), "v3 bundle missing --hln-ui-font-cjk-song token")
  assert.ok(bundle.includes("--hln-ui-font-cjk-kai:"), "v3 bundle missing --hln-ui-font-cjk-kai token")
  assert.ok(bundle.includes("--hln-ui-font-cjk-mono:"), "v3 bundle missing --hln-ui-font-cjk-mono token")
  assert.ok(bundle.includes("font-size-adjust: from-font"), "v3 bundle missing font-size-adjust: from-font")
  for (const cjk of HLN_V3_CJK_FONTS) {
    assert.ok(bundle.includes(`data-hln-cjk-font="${cjk}"`), `v3 bundle missing data-hln-cjk-font="${cjk}" rule`)
  }
})


