// ProjectHLN UI System v3.5 - Algorithmic Vector & Data-Stream Build Script (build.mjs)
import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const root = dirname(fileURLToPath(import.meta.url))
const srcDir = join(root, "src")
const distDir = join(root, "dist")

mkdirSync(distDir, { recursive: true })

const cssOrder = ["tokens.css", "themes.css", "base.css", "algorithmic.css"]
const passthrough = [...cssOrder, "index.js", "index.d.ts"]

for (const file of passthrough) {
  const content = readFileSync(join(srcDir, file), "utf8")
  writeFileSync(join(distDir, file), content, "utf8")
}

const banner =
  "/* ProjectHLN UI System v3.5 - Algorithmic Vector, AI-Native, Procedural & Data-Stream Edition. Do not edit; generated by v3.5/build.mjs. */\n"
const bundle =
  banner + cssOrder.map((file) => readFileSync(join(srcDir, file), "utf8")).join("\n")

writeFileSync(join(distDir, "hln-ui-system-v3.5.css"), bundle, "utf8")
console.log("v3.5 dist assembled; bundle bytes:", Buffer.byteLength(bundle, "utf8"))
