// ProjectHLN UI System v3.5 - Algorithmic Vector, AI-Native, Procedural & Data-Stream Contract Tests
import test from "node:test"
import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"
import {
  HLN_V35_THEMES,
  HLN_V35_THEME_REGISTRY,
  HLN_V35_FONTS,
  HLN_V35_CJK_FONTS,
  HLN_V35_BG_PRESETS,
  HLN_V35_MATH_CONSTANTS,
} from "./dist/index.js"

const Q = String.fromCharCode(34)
const v35 = dirname(fileURLToPath(import.meta.url))
const read = (rel) => readFileSync(join(v35, rel), "utf8")

const THEMES = [
  "singularity-cyan",
  "tensor-amber",
  "veridian-stream",
  "synapse-violet",
  "cobalt-manifold",
  "titanium-oxide",
  "alabaster-studio",
  "bauhaus-compiler",
]
const FONTS = ["geometric", "display", "technical", "grotesque", "cyber", "berlin", "editorial", "label"]
const CJK_FONTS = ["auto", "hei", "display", "song", "kai", "mono", "fangsong"]
const BG = [
  "tensor-stream",
  "neural-dag",
  "fourier-harmonics",
  "procedural-matrix",
  "simplex-contour",
  "clock-bus",
  "swiss-vector",
  "quiet",
]
const MOTION = [
  "panel",
  "item",
  "stream-cascade",
  "tensor-fold",
  "compile-lock",
  "wave-propagate",
  "vector-construct",
  "golden-iris",
  "rail-draw",
  "type-in",
  "page-shift",
]

test("v3.5 runtime registry exposes the 8 algorithmic vector & data-stream themes with zero game terminology", () => {
  assert.deepEqual([...HLN_V35_THEMES].sort(), [...THEMES].sort())
  assert.equal(HLN_V35_THEMES.length, 8)
  assert.deepEqual(HLN_V35_THEME_REGISTRY.map((t) => t.id).sort(), [...THEMES].sort())
  const bundle = read("dist/hln-ui-system-v3.5.css").toLowerCase()
  const js = read("dist/index.js").toLowerCase()
  for (const banned of ["prts", "arknights", "endfield", "rhodes", "blacksteel", "aegir", "babel", "rhine", "kazdel", "lungmen", "monster-siren"]) {
    assert.ok(!bundle.includes(banned), `v3.5 CSS bundle must not contain game term "${banned}"`)
    assert.ok(!js.includes(banned), `v3.5 JS runtime must not contain game term "${banned}"`)
  }
})

test("v3.5 mathematical constants are exact", () => {
  assert.ok(Math.abs(HLN_V35_MATH_CONSTANTS.PHI - 1.6180339887) < 1e-8)
  assert.ok(Math.abs(HLN_V35_MATH_CONSTANTS.SQRT2 - 1.4142135623) < 1e-8)
  assert.ok(Math.abs(HLN_V35_MATH_CONSTANTS.E - 2.7182818284) < 1e-8)
})

test("v3.5 source CSS defines all 8 algorithmic themes with zero blur", () => {
  const css = read("src/themes.css")
  for (const meta of HLN_V35_THEME_REGISTRY) {
    const blockStart = css.indexOf("data-hln-theme=" + Q + meta.id + Q)
    assert.notEqual(blockStart, -1, "src/themes.css missing block for " + meta.id)
    const block = css.slice(blockStart)
    const accent = block.match(/--hln-ui-accent:\s*([^;]+);/)
    const swatch = block.match(/--hln-ui-bg-1:\s*([^;]+);/)
    const scheme = block.match(/color-scheme:\s*([a-z]+);/)
    const blur = block.match(/--hln-ui-blur:\s*([^;]+);/)
    assert.equal(accent?.[1]?.trim(), meta.accent, meta.id + " accent mismatch vs CSS")
    assert.equal(swatch?.[1]?.trim(), meta.swatch, meta.id + " swatch mismatch vs CSS")
    assert.equal(scheme?.[1], meta.colorScheme, meta.id + " colorScheme mismatch vs CSS")
    assert.equal(blur?.[1]?.trim(), "0px", meta.id + " must enforce --hln-ui-blur: 0px")
  }
})

test("v3.5 dist mirrors source and bundle is current", () => {
  for (const f of ["tokens.css", "themes.css", "base.css", "algorithmic.css", "index.js", "index.d.ts"]) {
    assert.equal(read("dist/" + f), read("src/" + f), "dist/" + f + " drifted from src/" + f)
  }
  const banner = "/* ProjectHLN UI System v3.5 - Algorithmic Vector, AI-Native, Procedural & Data-Stream Edition. Do not edit; generated by v3.5/build.mjs. */\n"
  const expected = banner + ["tokens.css", "themes.css", "base.css", "algorithmic.css"].map((f) => read("src/" + f)).join("\n")
  assert.equal(read("dist/hln-ui-system-v3.5.css"), expected)
})

test("v3.5 algorithmic studio layer includes telemetry ribbon, procedural code box, DAG stage, harmonic spectrum, and attention matrix", () => {
  const alg = read("src/algorithmic.css")
  for (const cls of [
    "hln-v35-workbench",
    "hln-v35-ribbon",
    "hln-v35-sparkline",
    "hln-v35-compile-btn",
    "hln-v35-studio",
    "hln-v35-panel",
    "hln-v35-code-box",
    "hln-v35-latent-compass",
    "hln-v35-dag-stage",
    "hln-v35-packet-dot",
    "hln-v35-stage-track",
    "hln-v35-stream-bars",
    "hln-v35-attn-matrix",
    "hln-v35-eigen-list",
    "hln-v35-bus-log",
  ]) {
    assert.ok(alg.includes(cls), "src/algorithmic.css missing class " + cls)
  }
})

test("v3.5 fonts, CJK Hanzi stacks, backgrounds & motion match curated algorithmic sets", () => {
  assert.deepEqual([...HLN_V35_FONTS], FONTS)
  assert.deepEqual([...HLN_V35_CJK_FONTS], CJK_FONTS)
  assert.deepEqual(HLN_V35_BG_PRESETS.map((b) => b.id), BG)
  const bundle = read("dist/hln-ui-system-v3.5.css")
  for (const f of FONTS) assert.ok(bundle.includes("data-hln-font=" + Q + f + Q), "bundle missing font " + f)
  for (const cjk of CJK_FONTS) assert.ok(bundle.includes("data-hln-cjk-font=" + Q + cjk + Q), "bundle missing CJK font " + cjk)
  for (const k of MOTION) assert.ok(bundle.includes(k), "bundle missing motion " + k)
  for (const b of BG) assert.ok(bundle.includes("data-hln-bg-motion=" + Q + b + Q), "bundle missing bg preset " + b)
  assert.ok(bundle.includes("font-size-adjust: from-font"), "v3.5 bundle missing font-size-adjust: from-font")
})

test("artist-Paralos-main integrates v3.2 and v3.5 bundles and zero-display-bug CSS fallbacks", () => {
  const demoCss = read("../../artist-Paralos-main/styles/demo.css")
  const html = read("../../artist-Paralos-main/index.html")
  const syncedV32 = read("../../artist-Paralos-main/styles/hln-ui-system-v3.2.css")
  const syncedV35 = read("../../artist-Paralos-main/styles/hln-ui-system-v3.5.css")
  assert.equal(syncedV32, read("../v3.2/dist/hln-ui-system-v3.2.css"), "Paralos v3.2 CSS bundle out of sync")
  assert.equal(syncedV35, read("dist/hln-ui-system-v3.5.css"), "Paralos v3.5 CSS bundle out of sync")
  assert.ok(demoCss.includes("var(--hln-ui-glass, var(--hln-ui-bg-1))"), "demo.css topbar must fallback when --hln-ui-glass is absent")
  assert.ok(demoCss.includes("var(--hln-ui-glass-strong, var(--hln-ui-bg-1))"), "demo.css popover must fallback when --hln-ui-glass-strong is absent")
  assert.ok(html.includes('id="demo-layout-v35"'), "index.html missing #demo-layout-v35")
  assert.ok(html.includes('id="v35-latent-compass"') || html.includes('class="hln-v35-latent-compass"'), "index.html missing .hln-v35-latent-compass")
})

