// ProjectHLN UI System v3.8 - Cosmic Viewport Lens Contract Tests
import test from "node:test"
import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"
import {
  HLN_V38_THEMES,
  HLN_V38_THEME_REGISTRY,
  HLN_V38_FONTS,
  HLN_V38_CJK_FONTS,
  HLN_V38_BG_PRESETS,
  HLN_V38_MATH_CONSTANTS,
} from "./dist/index.js"

const Q = String.fromCharCode(34)
const v38 = dirname(fileURLToPath(import.meta.url))
const read = (rel) => readFileSync(join(v38, rel), "utf8")

const THEMES = [
  "cosmic-euclid",
  "pulsar-gold",
  "graviton-emerald",
  "supernova-crimson",
  "event-horizon",
  "orbital-station",
]
const FONTS = ["geometric", "display", "technical", "grotesque", "cyber", "berlin", "editorial", "label"]
const CJK_FONTS = ["auto", "hei", "display", "song", "kai", "mono", "fangsong"]
const BG = [
  "cosmic-geodesic",
  "stellar-spectrum",
  "pulsar-array",
  "celestial-sphere",
  "einstein-ring",
  "deep-space-lattice",
  "quiet",
]
const MOTION = [
  "panel",
  "item",
  "reticle-lock",
  "lensing-warp",
  "spectrum-scan",
  "orbit-sweep",
  "photon-pulse",
  "caliper-draw",
  "type-in",
  "page-shift",
]

test("v3.8 runtime registry exposes the 6 cosmic themes with zero game terminology", () => {
  assert.deepEqual([...HLN_V38_THEMES].sort(), [...THEMES].sort())
  assert.equal(HLN_V38_THEMES.length, 6)
  assert.deepEqual(HLN_V38_THEME_REGISTRY.map((t) => t.id).sort(), [...THEMES].sort())
  const bundle = read("dist/hln-ui-system-v3.8.css").toLowerCase()
  const js = read("dist/index.js").toLowerCase()
  for (const banned of ["prts", "arknights", "endfield", "rhodes", "blacksteel", "aegir", "babel", "rhine", "kazdel", "lungmen", "monster-siren"]) {
    assert.ok(!bundle.includes(banned), `v3.8 CSS bundle must not contain game term "${banned}"`)
    assert.ok(!js.includes(banned), `v3.8 JS runtime must not contain game term "${banned}"`)
  }
})

test("v3.8 mathematical and astrophysical constants are exact", () => {
  assert.ok(Math.abs(HLN_V38_MATH_CONSTANTS.PHI - 1.6180339887) < 1e-8)
  assert.ok(Math.abs(HLN_V38_MATH_CONSTANTS.SQRT2 - 1.4142135623) < 1e-8)
  assert.equal(HLN_V38_MATH_CONSTANTS.C_LIGHT, 299792458)
  assert.equal(HLN_V38_MATH_CONSTANTS.AU, 149597870700)
})

test("v3.8 source CSS defines all 6 cosmic themes with zero blur and zero shadow", () => {
  const css = read("src/themes.css")
  for (const meta of HLN_V38_THEME_REGISTRY) {
    const blockStart = css.indexOf("data-hln-theme=" + Q + meta.id + Q)
    assert.notEqual(blockStart, -1, "src/themes.css missing block for " + meta.id)
    const block = css.slice(blockStart)
    const accent = block.match(/--hln-ui-accent:\s*([^;]+);/)
    const swatch = block.match(/--hln-ui-bg-1:\s*([^;]+);/)
    const scheme = block.match(/color-scheme:\s*([a-z]+);/)
    const blur = block.match(/--hln-ui-blur:\s*([^;]+);/)
    assert.equal(accent?.[1]?.trim(), meta.accent, meta.id + " accent mismatch vs CSS")
    assert.equal(swatch?.[1]?.trim(), meta.swatch, meta.id + " swatch mismatch vs CSS")
    assert.equal(scheme?.[1], meta.colorScheme, meta.id + " colorScheme mismatch vs CSS")
    assert.equal(blur?.[1]?.trim(), "0px", meta.id + " must enforce --hln-ui-blur: 0px")
  }
})

test("v3.8 dist mirrors source and bundle is current", () => {
  for (const f of ["tokens.css", "themes.css", "base.css", "cosmic.css", "index.js", "index.d.ts"]) {
    assert.equal(read("dist/" + f), read("src/" + f), "dist/" + f + " drifted from src/" + f)
  }
  const banner = "/* ProjectHLN UI System v3.8 - Cosmic Viewport Lens & Astrophysics Telemetry Edition. Do not edit; generated by v3.8/build.mjs. */\n"
  const expected = banner + ["tokens.css", "themes.css", "base.css", "cosmic.css"].map((f) => read("src/" + f)).join("\n")
  assert.equal(read("dist/hln-ui-system-v3.8.css"), expected)
})

test("v3.8 cosmic observatory layer includes HUD ribbon, lens aperture, geodesic rays, spectrograph, absorption lines, and orbital state matrix", () => {
  const cos = read("src/cosmic.css")
  for (const cls of [
    "hln-v38-workbench",
    "hln-v38-viewport-frame",
    "hln-v38-frame-bezel",
    "hln-v38-bezel-top",
    "hln-v38-corner-clamp",
    "hln-v38-bezel-left",
    "hln-v38-bezel-right",
    "hln-v38-bezel-bottom",
    "hln-v38-glass-graticule",
    "hln-v38-viewport-inner",
    "hln-v38-hud",
    "hln-v38-hud-stream",
    "hln-v38-collimator",
    "hln-v38-console",
    "hln-v38-panel",
    "hln-v38-aperture-box",
    "hln-v38-geodesic-ray",
    "hln-v38-photon-dot",
    "hln-v38-spectrograph",
    "hln-v38-spectrum-rainbow",
    "hln-v38-abs-line",
    "hln-v38-orbital-grid",
    "hln-v38-metric-calipers",
    "hln-v38-telemetry-bus",
  ]) {
    assert.ok(cos.includes(cls), "src/cosmic.css missing class " + cls)
  }
})

test("v3.8 fonts, CJK Hanzi stacks, backgrounds & motion match curated cosmic sets", () => {
  assert.deepEqual([...HLN_V38_FONTS], FONTS)
  assert.deepEqual([...HLN_V38_CJK_FONTS], CJK_FONTS)
  assert.deepEqual(HLN_V38_BG_PRESETS.map((b) => b.id), BG)
  const bundle = read("dist/hln-ui-system-v3.8.css")
  for (const f of FONTS) assert.ok(bundle.includes("data-hln-font=" + Q + f + Q), "bundle missing font " + f)
  for (const cjk of CJK_FONTS) assert.ok(bundle.includes("data-hln-cjk-font=" + Q + cjk + Q), "bundle missing CJK font " + cjk)
  for (const k of MOTION) assert.ok(bundle.includes(k), "bundle missing motion " + k)
  assert.ok(bundle.includes("font-size-adjust: from-font"), "v3.8 bundle missing font-size-adjust: from-font")
})

test("artist-Paralos-main integrates v3.8 cosmic viewport bundle and runtime handlers", () => {
  const demoCss = read("../../artist-Paralos-main/styles/demo.css")
  const html = read("../../artist-Paralos-main/index.html")
  const appJs = read("../../artist-Paralos-main/app.js")
  const syncedV38 = read("../../artist-Paralos-main/styles/hln-ui-system-v3.8.css")
  assert.equal(syncedV38, read("dist/hln-ui-system-v3.8.css"), "Paralos v3.8 CSS bundle out of sync")
  assert.ok(demoCss.includes('[data-showcase-view="v38"]'), "demo.css missing v38 visibility rules")
  assert.ok(html.includes('id="demo-layout-v38"'), "index.html missing v38 demo layout")
  assert.ok(html.includes('data-ui-version="v3.8"'), "index.html missing v3.8 version switcher button")
  assert.ok(appJs.includes("themesV38"), "app.js missing themesV38")
  assert.ok(appJs.includes("bgPresetsV38"), "app.js missing bgPresetsV38")
  assert.ok(appJs.includes("motionActionsV38"), "app.js missing motionActionsV38")
  assert.ok(appJs.includes('"styles/hln-ui-system-v3.8.css"'), "app.js missing v3.8 stylesheet map")
  assert.ok(appJs.includes("#v38-slider-mass"), "app.js missing v3.8 mass slider handler")
})

